### PR TITLE
Reduce 'color-by' options

### PR DESCRIPTION
**Pull request by ellisrichardj**
This PR makes a number of small changes, the most significant of which is the reduction in metadata categories which can be selected in the Nextstrain drop-down to change the colour of the branch tips and markers on the map.  Not all of these were required or provided useful information when displayed.   There are also minor changes to balance the resources (`maxForks`) available to each process in an effort to reduce overall runtime of the pipeline and the addition of one more sample in the list of outliers.

### CODE REVIEW

**Review by nick-pestell — APPROVED** [review]
Looks good. I actually don't understand the difference between `cpus` and `maxForks` directives even after reading the docs, I asked a question on the Nextflow slack. Anyway, I'm sure you've got a handle on it so happy to approve!

**Comment by ellisrichardj** [comment]
> Looks good. I actually don't understand the difference between `cpus` and `maxForks` directives even after reading the docs, I asked a question on the Nextflow slack. Anyway, I'm sure you've got a handle on it so happy to approve!

`maxForks` is the number of instances of that particular process that can be running at any one time and `cpus` is the number of cores each process can use.  Say you have 6 items waiting in the queue on an 4-core machine, you could ensure that 4 are processed in parallel by setting `maxForks = 4` and it will then start the 5th item as soon as any one of them has finished, or have one process using all 4-cores using `cpus = 4`, meaning that each process will run sequentially.

**Comment by nick-pestell** [comment]
> > Looks good. I actually don't understand the difference between `cpus` and `maxForks` directives even after reading the docs, I asked a question on the Nextflow slack. Anyway, I'm sure you've got a handle on it so happy to approve!
> 
> `maxForks` is the number of instances of that particular process that can be running at any one time and `cpus` is the number of cores each process can use. Say you have 6 items waiting in the queue on an 4-core machine, you could ensure that 4 are processed in parallel by setting `maxForks = 4` and it will then start the 5th item as soon as any one of them has finished, or have one process using all 4-cores using `cpus = 4`, meaning that each process will run sequentially.

Ok, but, am I right in thinking then that in your second example, this would only be of benefit for a process definition that is able to leverage multiple cores? I.e. if your process itself is single threaded, then you gain nothing by setting `cpus=4`?

**Comment by ellisrichardj** [comment]
> > > Looks good. I actually don't understand the difference between `cpus` and `maxForks` directives even after reading the docs, I asked a question on the Nextflow slack. Anyway, I'm sure you've got a handle on it so happy to approve!
> > 
> > 
> > `maxForks` is the number of instances of that particular process that can be running at any one time and `cpus` is the number of cores each process can use. Say you have 6 items waiting in the queue on an 4-core machine, you could ensure that 4 are processed in parallel by setting `maxForks = 4` and it will then start the 5th item as soon as any one of them has finished, or have one process using all 4-cores using `cpus = 4`, meaning that each process will run sequentially.
> 
> Ok, but, am I right in thinking then that in your second example, this would only be of benefit for a process definition that is able to leverage multiple cores? I.e. if your process itself is single threaded, then you gain nothing by setting `cpus=4`?

Yes - exactly

**Review by Hira-Naveed — APPROVED** [review]
Looks like a great update to clean up the interface and thank you for explaining maxForks too!

**Pull request merged**
