### PR TITLE
Post process snp matrix

### PR DESCRIPTION
**Pull request by nick-pestell**
This PR fixes the sample names in the snp matrix output so that they are instead submission numbers. This is needed for pairing with metadata.

* A new script, `extractSub.sh` is created which serves only to convert a sample name into a submission number, with code ripped from the original `addsub.sh` file. This is because this routine is now used twice.
* `addsub.sh` is adapted to utilise this new script.
*  A new script `postprocessMatrix.sh` processes the snp matricies to change row and column names into submission numbers using `extractSub.sh` - this reads sample names into an array (line 12), loops through the array extracting the submission number and appending to a new array. The new snp_matrix header is written on line 20. Subsequent lines are written to the snp matrix in a loop, (line 26).
* The running of the `postprocessMatrix.sh` script is appended to the `cladematrix` nf process: `build_matrix.sh` outputs an intermediary file `snp_matrix.csv` which is read in by `postprocessMatrix.sh`.

I am not sure how NF deals with staging scripts, I'm not sure if the `extractSub.sh` script will be staged correctly, since it isn't explicitly called within the NF command. I.e. I'm concerned it won't be present in the required work folder.

### CODE REVIEW

**Comment by nick-pestell** [comment]
Closing for now due to a bug

**Comment by nick-pestell** [comment]
Just had a thought that it may be quicker /  better to add the postprocessing stage to `concatconsensus.sh` so that the fasta file has submission numbers rather than post processing the SNP matrix. 

Could be somehow bolted onto line26- `concatConsensus.sh` ... thoughts?

**Comment by ellisrichardj** [comment]
> Just had a thought that it may be quicker / better to add the postprocessing stage to `concatconsensus.sh` so that the fasta file has submission numbers rather than post processing the SNP matrix.
> 
> Could be somehow bolted onto line26- `concatConsensus.sh` ... thoughts?

I think the main issue is that we could end up with conflicts - multiple samples could end up with the same submission number and hence we get multiple branches on the tree or lines in the matrix labelled the same submission with no way to track back to the original sample.

**Comment by ellisrichardj** [comment]
Correct me if I'm wrong, but I think what's happening here is that you have isolated the `extractsub` function and run it each time the conversion is needed.  So that means its run once for appending it to the metadata, and then again to do the swap in the matrix.  Would it be more efficient to run it once and then have a look up function?  Or, alternatively, link the snp matrix to the clademetadata output, which has a link to both submission and sample number?

**Comment by nick-pestell** [comment]
Yes, that is the idea. I think you're right it would be more efficient to do it with a look up table, that's a good point. Though, I think the majority of the overhead is probably in reading and writing files line-by-line, e.g. line9 in `addsub` and line 23 in `postprocessMatrix`. 

Perhaps the best option would actually be just to export the fully filtered WGS metadata (with submission number) to the sqlite db. And then as you say retrieve the submission number from this in ViewBovine backend. Which file would it be to export to the sqlite db?

**Comment by nick-pestell** [comment]
No longer required due to https://github.com/APHA-CSU/btb-forestry/pull/19#issue-1608763366

**Pull request closed without merging**
