### PR TITLE
Add additional fix for Gender column

### PR DESCRIPTION
**Pull request by ellisrichardj**
This PR is to add some additional steps in the metadata filtering (removing spaces and Ns from the Gender column) which will hopefully address the search issue.

### CODE REVIEW

**Comment by ellisrichardj** [comment]
Sorry - I will need to update some tests.......

**Comment by ellisrichardj** [comment]
I have now updated the test data files to match the data we now get from the metadata warehouse, and the expected outputs

**Comment by nick-pestell** [comment]
Thanks Richard, I wonder if we should test the outputs with the ViewBovis API, i.e. the sqlite database...

Happy to forgo this step if you're confident that it'll work though

**Comment by ellisrichardj** [comment]
> Thanks Richard, I wonder if we should test the outputs with the ViewBovis API, i.e. the sqlite database...
> 
> Happy to forgo this step if you're confident that it'll work though

Good idea.  I've now taken a look and the sqlite database is generated from the raw input rather than this filtered version.  Will test a few more options

**Comment by ellisrichardj** [comment]
I've now added some additional steps when generating the database to ensure that erroneous entries are properly captured as empty.  This then works in conjunction with [PR124](https://github.com/aphascience/ViewBovis/pull/124) in ViewBovis

**Review by Hira-Naveed — APPROVED** [review]
Looking great Richard and good to get this in!

**Pull request merged**
